kind: Service
apiVersion: v1

metadata:
  labels:
    app: jenkins
  name: jenkins-service
  namespace: usine-logicielle

spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    targetPort: 8080
  selector:
    app: jenkins
