kind: Service
apiVersion: v1

metadata:
  labels:
    app: usine-logicielle
  name: usine-service
  namespace: usine-logicielle

spec:
  type: NodePort
  ports:
  - port: 8080
    name: "interface"
    nodePort: 30002
    targetPort: 8080
  - port: 50000
    name: "slave"
    nodePort: 30010
    targetPort: 50000
  selector:
    app: usine-logicielle
